import { Cafe } from '../types';

export const mockCafes: Cafe[] = [
  {
    id: 1,
    name: '光景 Scene Select',
    address: '台北市中山區新生北路一段11-5號',
    hours: '12:00 - 19:00',
    imageUrl: 'https://picsum.photos/seed/cafe1/600/400',
    description: '藏身在巷弄中的一片靜謐，工業風設計搭配溫暖木質，是靈感與咖啡因碰撞的完美場所。',
    seats: {
      total: { total: 30, available: 12 },
      outlet: { total: 15, available: 5 },
      window: { total: 8, available: 2 },
      noAc: { total: 10, available: 6 },
    },
    menu: [
      { id: 101, name: '手沖單品', price: 180, category: '咖啡', description: '每日精選不同產區的咖啡豆，風味獨特。' },
      { id: 102, name: '拿鐵', price: 150, category: '咖啡', description: '濃郁義式濃縮與綿密奶泡的完美結合。' },
      { id: 103, name: '京都抹茶歐蕾', price: 160, category: '茶飲', description: '使用日本進口抹茶粉，茶香濃郁。' },
      { id: 104, name: '巴斯克乳酪蛋糕', price: 140, category: '甜點', description: '表面焦香，內心濕潤綿密。' },
      { id: 105, name: '酪梨雞肉三明治', price: 220, category: '輕食', description: '新鮮酪梨搭配舒肥雞胸肉，健康美味。' },
    ],
    reviews: [
      { id: 1001, author: 'Coding Maniac', rating: 5, comment: '插座很多，網路很快，完全是我的行動辦公室首選！咖啡也好喝。' },
      { id: 1002, author: '書蟲少女', rating: 5, comment: '靠窗的位置陽光灑進來超美，很適合安靜看書一個下午。' },
    ],
    averageRating: 5,
    reviewGrowth: 0.2,
    tags: ['社畜', '書蟲', '黃光派'],
  },
  {
    id: 2,
    name: '隅室 The Corner',
    address: '台北市大安區忠孝東路四段216巷32弄1號',
    hours: '11:00 - 20:00',
    imageUrl: 'https://picsum.photos/seed/cafe2/600/400',
    description: '城市中的溫馨角落，提供手作甜點與精品咖啡，讓你暫時忘卻煩憂。',
    seats: {
      total: { total: 22, available: 5 },
      outlet: { total: 8, available: 1 },
      window: { total: 6, available: 0 },
      noAc: { total: 12, available: 4 },
    },
    menu: [
      { id: 201, name: '卡布奇諾', price: 140, category: '咖啡', description: '經典風味，肉桂粉或可可粉可供選擇。' },
      { id: 202, name: '莓果森林氣泡飲', price: 170, category: '茶飲', description: '新鮮莓果醬搭配清爽氣泡水，夏日首選。' },
      { id: 203, name: '法式鹹派', price: 180, category: '輕食', description: '每日現烤，口味依當日食材決定。' },
      { id: 204, name: '檸檬糖霜磅蛋糕', price: 130, category: '甜點', description: '酸甜滋味，口感扎實濕潤。' },
    ],
    reviews: [
      { id: 2001, author: '甜點愛好者', rating: 5, comment: '他們家的磅蛋糕真的太神了！每次來必點，座位有點少，建議早點來。' },
      { id: 2002, author: '巷口小王', rating: 4, comment: '氣氛很好，但冷氣口的位置真的有點冷，下次會選裡面的位子。' },
    ],
    averageRating: 4.5,
    reviewGrowth: 0.15,
    tags: ['復古咖', '黃光派', '長舌局'],
  },
  {
    id: 3,
    name: '日常 Daily Normal',
    address: '台北市信義區松高路11號',
    hours: '09:00 - 22:00',
    imageUrl: 'https://picsum.photos/seed/cafe3/600/400',
    description: '簡約明亮的空間，提供快速、高品質的咖啡與餐點，是上班族與購物客的綠洲。',
    seats: {
      total: { total: 50, available: 25 },
      outlet: { total: 20, available: 11 },
      window: { total: 15, available: 8 },
      noAc: { total: 30, available: 20 },
    },
    menu: [
        { id: 301, name: '美式咖啡', price: 110, category: '咖啡', description: '快速提神的最佳選擇。' },
        { id: 302, name: '冰搖檸檬茶', price: 120, category: '茶飲', description: '清爽解膩，酸甜適中。' },
        { id: 303, name: '燻雞可頌', price: 90, category: '輕食', description: '外皮酥脆，內餡飽滿。' },
        { id: 304, name: '巧克力豆軟餅乾', price: 70, category: '甜點', description: '現烤出爐，溫暖你的心。' }
    ],
    reviews: [
        { id: 3001, author: '趕時間的業務', rating: 4, comment: '出餐速度很快，咖啡品質穩定，在信義區是個方便的好選擇。' },
        { id: 3002, author: '逛街累了', rating: 4, comment: '位子很多，不怕沒地方坐。冷氣不會直吹的區域很棒，可以好好休息。' }
    ],
    averageRating: 4.0,
    reviewGrowth: 0.25,
    tags: ['社畜', '潮流咖'],
  },
  {
    id: 4,
    name: '鍊金術師的角落',
    address: '台北市中正區羅斯福路三段283巷14弄',
    hours: '14:00 - 23:00',
    imageUrl: 'https://picsum.photos/seed/cafe4/600/400',
    description: '蒸汽龐克風格的獨特空間，專注於虹吸式咖啡的奇幻體驗，每一杯都是一場表演。',
    seats: {
      total: { total: 25, available: 8 },
      outlet: { total: 10, available: 3 },
      window: { total: 5, available: 1 },
      noAc: { total: 15, available: 7 },
    },
    menu: [
      { id: 401, name: '虹吸壺單品', price: 250, category: '咖啡', description: '觀賞性十足的沖煮過程，風味純淨。' },
      { id: 402, name: '焦糖海鹽拿鐵', price: 170, category: '咖啡', description: '甜鹹交織的迷人風味。' },
      { id: 403, name: '提拉米蘇', price: 150, category: '甜點', description: '帶有濃厚酒香的大人味甜點。' },
    ],
    reviews: [
      { id: 4001, author: '風格追求者', rating: 5, comment: '裝潢太酷了！好像來到另一個時空，虹吸咖啡也很有趣。' },
    ],
    averageRating: 4.8,
    reviewGrowth: 0.18,
    tags: ['復古咖', '潮流咖', '科技感', '特殊動物'],
  },
  {
    id: 5,
    name: '都市綠洲 Urban Oasis',
    address: '台北市內湖區瑞光路513巷22弄',
    hours: '10:00 - 18:00',
    imageUrl: 'https://picsum.photos/seed/cafe5/600/400',
    description: '充滿綠色植物的玻璃屋咖啡廳，陽光灑落，彷彿在城市中找到一片寧靜的綠洲。',
    seats: {
      total: { total: 40, available: 15 },
      outlet: { total: 18, available: 9 },
      window: { total: 20, available: 10 },
      noAc: { total: 25, available: 12 },
    },
    menu: [
      { id: 501, name: '西西里咖啡', price: 160, category: '咖啡', description: '檸檬清香與濃縮咖啡的完美碰撞。' },
      { id: 502, name: '花草茶', price: 150, category: '茶飲', description: '多種有機花草選擇，舒緩身心。' },
      { id: 503, name: '水果優格碗', price: 250, category: '輕食', description: '新鮮水果、堅果與希臘優格的健康組合。' },
    ],
    reviews: [
      { id: 5001, author: '網美攝影師', rating: 5, comment: '採光超棒，每個角落都好拍！餐點也很健康，適合怕胖的我。' },
    ],
    averageRating: 4.6,
    reviewGrowth: 0.22,
    tags: ['潮流咖', '書蟲', '黃光派'],
  },
  {
    id: 6,
    name: '慵懶貓咖',
    address: '台北市萬華區西寧南路123號',
    hours: '13:00 - 21:00 (週二公休)',
    imageUrl: 'https://picsum.photos/seed/cafe6/600/400',
    description: '溫馨的木質調空間，有數隻可愛的店貓四處走動，是貓奴們的療癒天堂。',
    seats: {
      total: { total: 28, available: 10 },
      outlet: { total: 10, available: 4 },
      window: { total: 8, available: 3 },
      noAc: { total: 18, available: 7 },
    },
    menu: [
      { id: 601, name: '貓掌棉花糖可可', price: 180, category: '茶飲', description: '可愛又好喝，融化你的心。' },
      { id: 602, name: '鮪魚鬆餅', price: 200, category: '輕食', description: '鹹口味鬆餅，貓咪也愛的味道。' },
    ],
    reviews: [
      { id: 6001, author: '重度貓奴', rating: 5, comment: '貓咪都好親人，環境也很乾淨，待上一整個下午都沒問題！' },
    ],
    averageRating: 4.9,
    reviewGrowth: 0.3,
    tags: ['貓派', '黃光派'],
  },
  {
    id: 7,
    name: '午夜肝廠',
    address: '台北市松山區南京東路五段66巷2弄',
    hours: '24小時營業',
    imageUrl: 'https://picsum.photos/seed/cafe7/600/400',
    description: '專為夜貓子和SOHO族打造的空間，提供穩定的網路、充足插座和無限續杯的美式咖啡。',
    seats: {
      total: { total: 60, available: 30 },
      outlet: { total: 50, available: 25 },
      window: { total: 10, available: 5 },
      noAc: { total: 40, available: 20 },
    },
    menu: [
      { id: 701, name: '無限續杯美式', price: 200, category: '咖啡', description: '憑杯無限暢飲，熬夜必備。' },
      { id: 702, name: '深夜泡麵', price: 100, category: '輕食', description: '你懂的，就是那個撫慰人心的味道。' },
    ],
    reviews: [
      { id: 7001, author: '爆肝工程師', rating: 5, comment: '半夜唯一的去處，感謝老闆！' },
    ],
    averageRating: 4.2,
    reviewGrowth: 0.1,
    tags: ['社畜'],
  },
  {
    id: 8,
    name: '外婆的食譜',
    address: '台北市大同區迪化街一段123號',
    hours: '11:00 - 18:00',
    imageUrl: 'https://picsum.photos/seed/cafe8/600/400',
    description: '藏身於大稻埕的老宅咖啡廳，提供遵循古法製作的傳統點心與茶飲，每一口都是回憶。',
    seats: {
      total: { total: 20, available: 6 },
      outlet: { total: 5, available: 1 },
      window: { total: 6, available: 2 },
      noAc: { total: 14, available: 5 },
    },
    menu: [
      { id: 801, name: '杏仁茶與油條', price: 150, category: '茶飲', description: '濃醇杏仁茶搭配現炸油條，絕配。' },
      { id: 802, name: '桂花糕', price: 90, category: '甜點', description: '清香淡雅，口感Q彈。' },
    ],
    reviews: [
      { id: 8001, author: '懷舊旅人', rating: 5, comment: '很有味道的地方，點心都好好吃，讓人想起小時候。' },
    ],
    averageRating: 4.7,
    reviewGrowth: 0.12,
    tags: ['復古咖', '黃光派', '長舌局'],
  },
  {
    id: 9,
    name: '藝廊咖啡',
    address: '台北市中山區中山北路二段44巷2號',
    hours: '11:00 - 19:00',
    imageUrl: 'https://picsum.photos/seed/cafe9/600/400',
    description: '結合藝術展覽的複合式空間，定期更換展品，讓你在藝術氛圍中品味咖啡。',
    seats: {
      total: { total: 35, available: 11 },
      outlet: { total: 12, available: 5 },
      window: { total: 10, available: 4 },
      noAc: { total: 20, available: 8 },
    },
    menu: [
      { id: 901, name: '維也納咖啡', price: 160, category: '咖啡', description: '濃郁黑咖啡覆蓋上冰涼鮮奶油，口感層次豐富。' },
      { id: 902, name: '可麗露', price: 100, category: '甜點', description: '外脆內軟，帶有蘭姆酒與香草香氣。' },
    ],
    reviews: [
      { id: 9001, author: '文藝青年', rating: 4, comment: '可以一邊看展一邊喝咖啡，很棒的體驗。' },
    ],
    averageRating: 4.5,
    reviewGrowth: 0.16,
    tags: ['潮流咖', '書蟲', '特殊動物'],
  },
  {
    id: 10,
    name: 'The Minimalist',
    address: '台北市大安區敦化南路一段161巷7弄',
    hours: '09:00 - 19:00',
    imageUrl: 'https://picsum.photos/seed/cafe10/600/400',
    description: '純白色的極簡設計空間，屏除一切多餘的裝飾，讓你專注於每一杯咖啡的純粹風味。',
    seats: {
      total: { total: 26, available: 9 },
      outlet: { total: 10, available: 3 },
      window: { total: 6, available: 2 },
      noAc: { total: 16, available: 7 },
    },
    menu: [
      { id: 1001, name: '濃縮咖啡', price: 100, category: '咖啡', description: '考驗咖啡豆品質與咖啡師技術的精髓。' },
      { id: 1002, name: '小白咖啡 (Flat White)', price: 140, category: '咖啡', description: '比拿鐵更絲滑的口感，奶泡薄而細緻。' },
    ],
    reviews: [
      { id: 10001, author: '咖啡狂熱者', rating: 5, comment: '真正懂咖啡的人一定要來，他們的豆子真的很棒。' },
    ],
    averageRating: 4.8,
    reviewGrowth: 0.19,
    tags: ['潮流咖'],
  },
  {
    id: 11,
    name: '讀冊角落',
    address: '台北市文山區指南路二段123號',
    hours: '13:00 - 22:00',
    imageUrl: 'https://picsum.photos/seed/cafe11/600/400',
    description: '圖書館般的靜謐氛圍，擁有整面牆的書櫃，是需要專注工作或沉浸書海的最佳去處。',
    seats: {
      total: { total: 45, available: 18 },
      outlet: { total: 30, available: 12 },
      window: { total: 10, available: 3 },
      noAc: { total: 30, available: 15 },
    },
    menu: [
      { id: 1101, name: '鍋煮奶茶', price: 180, category: '茶飲', description: '香料與紅茶、牛奶的溫暖結合。' },
      { id: 1102, name: '布朗尼', price: 130, category: '甜點', description: '加熱後搭配冰淇淋，是閱讀時的最佳良伴。' },
    ],
    reviews: [
      { id: 11001, author: '研究生', rating: 5, comment: '超級安靜，是我寫論文的神聖殿堂。' },
    ],
    averageRating: 4.6,
    reviewGrowth: 0.14,
    tags: ['書蟲', '黃光派', '社畜'],
  },
  {
    id: 12,
    name: '毛絨絨天堂',
    address: '台北市士林區文林路456號',
    hours: '12:00 - 20:00',
    imageUrl: 'https://picsum.photos/seed/cafe12/600/400',
    description: '明亮現代風格的貓咪咖啡廳，空間寬敞，貓咪們都有充足的活動空間，療癒感滿分。',
    seats: {
      total: { total: 38, available: 14 },
      outlet: { total: 15, available: 6 },
      window: { total: 12, available: 5 },
      noAc: { total: 25, available: 10 },
    },
    menu: [
      { id: 1201, name: '水果千層蛋糕', price: 190, category: '甜點', description: '新鮮水果與滑順卡士達的層層堆疊。' },
      { id: 1202, name: '玫瑰氣泡飲', price: 160, category: '茶飲', description: '夢幻的粉色飲品，拍照首選。' },
    ],
    reviews: [
      { id: 12001, author: '愛貓人士', rating: 5, comment: '環境很好，對貓咪很友善，甜點也好吃，一定會再訪！' },
    ],
    averageRating: 4.7,
    reviewGrowth: 0.28,
    tags: ['貓派', '潮流咖'],
  },
  {
    id: 13,
    name: '電力補給站',
    address: '台北市南港區經貿二路188號',
    hours: '08:00 - 20:00',
    imageUrl: 'https://picsum.photos/seed/cafe13/600/400',
    description: '專為遠距工作者與商務人士設計，提供會議室租借、高速網路與齊全的辦公設備。',
    seats: {
      total: { total: 70, available: 40 },
      outlet: { total: 60, available: 35 },
      window: { total: 15, available: 8 },
      noAc: { total: 50, available: 30 },
    },
    menu: [
      { id: 1301, name: '貝果套餐', price: 180, category: '輕食', description: '多種口味貝果搭配奶油乳酪與一杯美式咖啡。' },
      { id: 1302, name: '能量果昔', price: 200, category: '茶飲', description: '用新鮮蔬果為你補充能量。' },
    ],
    reviews: [
      { id: 13001, author: '數位遊牧民族', rating: 4, comment: '插座真的很多，網路也超快，開會或工作都很方便。' },
    ],
    averageRating: 4.4,
    reviewGrowth: 0.21,
    tags: ['社畜', '科技感'],
  },
];